name: Build WASM

on:
  push:
    branches:
      - main

env:
  RUST_VERSION: 1.86.0
  TRUNK_VERSION: 0.21.13
  CACHE_TIER: ${{ (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/')) && 'prd' || 'dev' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: wasm32-unknown-unknown
      - name: Cache rust dependencies and tools
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
          shared-key: ${{ env.CACHE_TIER }}
          cache-on-failure: true
      - name: Install tools
        run: |
          cargo install -f --locked trunk --version ${{ env.TRUNK_VERSION }}
      - name: Build
        run: |
          trunk build --release --public-url /rhb
